name: Get Citation Data

on: 
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        # 修正路径：指向文件夹里的 requirements.txt
        pip install -r google_scholar_crawler/requirements.txt

    - name: Run Crawler
      env: 
        GOOGLE_SCHOLAR_ID: bsoUm7sAAAAJ
      run: |
        # 修正路径：运行文件夹里的 main.py
        python3 google_scholar_crawler/main.py

    - name: Push to Branch
      run: |
        # 因为 main.py 是在根目录被调用的，所以生成的 results 文件夹会在根目录
        # 直接进入 results 文件夹
        cd results
        
        git init
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        
        git add *.json
        git commit -m "Updated Citation Data"
        
        # 强制推送到 google-scholar-stats 分支
        git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:google-scholar-stats --force